<div class="row">
    <div class="col-xs-12 col-md-3">
        <div class="product-text-tab-container">
            <ul class="nav-tabs product-text-tab">
                <?php $ctr = 0; foreach ($this->languages As $val):?>
                    <li class="<?php echo ($ctr++) ?: 'active'?>">
                        <a class="clearfix" data-toggle="tab" href="#moduletpl-text-transaltions-<?php echo $this->id . '-' . $val['lang_cms_locale']?>" aria-expanded="false">
                            <?php echo $val['lang_label']?>
                        </a>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
    <div class="col-xs-12 col-md-9">
        <div class="tab-content">
            <?php $ctr = 0; foreach ($this->langForm As $key => $form):?>
                <div id="moduletpl-text-transaltions-<?php echo $this->id . '-' .$key ?>" class="tab-pane <?php echo ($ctr++) ? '': 'active'?>">
                    <?php
                        $form->prepare();
                        $form->setAttribute('id', $form->getAttribute('id').'-'.$key);
                        echo $this->form()->openTag($form);
                        echo $this->melisFieldCollection($form);
                        echo $this->form()->closeTag();
                    ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
</div>
