<?php
    $id = $this->zoneconfig['conf']['id'];
    $melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<div id="<?php echo $id ?>" data-melisKey="<?php echo $melisKey; ?>">
    <div class="me-heading bg-white border-bottom" id="id_meliscore_tool_user_header" data-meliskey="meliscore_tool_user_header">
        <div class="row">
            <div class="me-hl col-xs-8 col-sm-8 col-md-8">
                <h1 class="content-heading"><?php echo $this->translate('tr_moduletpl_title')?></h1>
                <?php if ($this->translate('tr_moduletpl_desc') != 'tr_moduletpl_desc') {?>
                    <p><?= $this->translate('tr_moduletpl_desc'); ?></p>
                <?php } ?>
            </div>
            <div class="me-hl col-xs-4 col-sm-4 col-md-4">
                <button class="btn btn-success btnAddModuleTpl pull-right"  title="<?php echo $this->translate('tr_moduletpl_common_button_add'); ?>"><i class="fa fa-plus"></i> <?php echo $this->translate('tr_moduletpl_common_add_item'); ?></button>
            </div>
        </div>
    </div>
</div>