<?php
    $id = $this->id . '_' . $this->zoneconfig['conf']['id'];
    $melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<div id="<?php echo $id ?>" data-melisKey="<?php echo $melisKey; ?>">
    <div id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
        <div class="widget-head nav">
            <ul class="tabs-label nav-tabs">
                <?php
                    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {

                        $tabId = $this->id . '_' . $menuConfig['conf']['id'];
                        $tabIcon = $menuConfig['conf']['icon'];
                        $tabName = $menuConfig['conf']['name'];

                        $li= '<li>
                            <a class="'.$tabIcon.'" data-toggle="tab" href="#'.$tabId.'" aria-expanded="true">
                                <i></i>
                                <span>'.$this->translate($tabName).'</span>
                            </a>
                        </li>';
                        echo $li;
                    }
                ?>
            </ul>
        </div>
    </div>
    <div class="tab-content innerAll spacing-x2">
        <?php
            if(!empty($this->zoneconfig['interface'])){
                foreach($this->zoneconfig['interface'] as $keyConfig => $val){
                    echo $this->$keyConfig;
                }
            }
        ?>
    </div>
</div>


