<?php
    $id = $this->zoneconfig['conf']['id'];
    $melisKey = $this->melisKey;
?>
<div class="tab-pane container-level-a" id="<?php echo $id; ?>" data-melisKey="<?php echo $melisKey; ?>">
    <?php
        if(!empty($this->zoneconfig['interface']))
        {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
            {
                echo $this->$keyConfig;
            }
        }
    ?>
</div>

