<ul data-type="<?php echo $this->type ?>">
    <?php
    foreach ($this->tables As $tbl){
        $icon = 'fa-square-o';
        if ($tbl->getName() == $this->selectedTbl){
            $icon = 'fa-check-square-o text-success';
        }

        $hasPrimaryTbl = null;
        if (!empty($this->selectedPrimaryTbl))
            if ($this->selectedPrimaryTbl == $tbl->getName())
                $hasPrimaryTbl = 'class="melis-toolcreator-disable-db-tbl-item"';

        echo '<li data-table-name="'.$tbl->getName().'" '.$hasPrimaryTbl.'>
                <span><i class="fa '.$icon.' fa-lg"></i> '.$tbl->getName().'</span>
            </li>';
    }
    ?>
</ul>
<?php
    $form = $this->step3Form;
    $form->setAttribute('id', $form->getAttribute('id').'-'.$this->type);
    echo $this->form()->openTag($form);
    echo $this->formCollection($form, false);
    echo $this->form()->closeTag();
