<style>
    .tcf-lbl-balance{
        height: 14px;
    }
</style>
<div id="<?php echo $this->id; ?>" class="steps-content">
    <div class="row">
        <div class="col-sm-12 margin-bottom-10">
            <h3><?php echo $this->translate('tr_melistoolcreator_cols_translations_title') ?></h3>
            <p><?php echo $this->translate('tr_melistoolcreator_cols_translations_desc') ?></p>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="product-text-tab-container">
                <ul class="nav-tabs product-text-tab">
                    <?php $ctr = 0; foreach ($this->languages As $key => $val):?>
                        <li class="<?php echo ($ctr++) ?: 'active'?>">
                            <a class="clearfix" data-toggle="tab" href="#toolcreator-text-transaltions-<?php echo $val['lang_locale']?>" aria-expanded="false">
                                <?php echo $val['lang_label']?>
                            </a>
                        </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
        <div class="col-xs-12 col-md-9">
            <div class="tab-content">
                <?php $ctr = 0; foreach ($this->step6Form As $key => $form):?>
                    <div id="toolcreator-text-transaltions-<?php echo $key ?>" class="tab-pane <?php echo ($ctr++) ? '': 'active'?>">
                        <?php
                            foreach ($form As $tblType => $tblForm){

                                if (count($form) > 1){
                                    echo '<h4>'.$this->translate('tr_melistoolcreator_'.$tblType).'</h4>';
                                }

                                $tblForm->setAttribute('style', 'margin-bottom: 20px');
                                $tblForm->prepare();

                                echo $this->form()->openTag($tblForm);

                                foreach ($tblForm->getElements() As $key => $val){

                                    if ($val->getOption('col-name'))
                                        echo '<div class="row">';

                                    if ($val->getLabel() || $val->getOption('col-desc')){
                                        if (!empty($this->formElementErrors($val))){
                                            $val->setLabelAttributes(array('class' => 'text-danger'));
                                        }

                                        if ($val->getOption('col-name'))
                                            echo '<div class="col-md-4">';

                                        if ($val->getOption('col-desc')){
                                            $val->setLabel(' ');
                                            $val->setLabelAttributes(array('class' => 'tcf-lbl-balance'));
                                            echo '<div class="col-md-8">';
                                        }

                                        echo '<div class="form-group">';

                                        if ($tblType == 'lang_tbl'){
                                            // Removing language col prefix to display
                                            $val->setLabel(str_replace('tclangtblcol_', '', $val->getLabel()));
                                        }

                                        echo $this->formLabel($val);
                                    }

                                    echo $this->formElement($val);

                                    if ($val->getLabel() || $val->getOption('col-desc')){
                                        echo $this->formElementErrors($val, array('class' => 'text-danger'));
                                        echo '</div></div>';
                                    }

                                    if ($val->getOption('col-desc'))
                                        echo '</div>';
                                }

                                echo $this->form()->closeTag();
                            }
                        ?>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    </div>

    <button class="btn btn-default btn-steps" data-curstep="6" data-nxtstep="5"><?php echo $this->translate('tr_melistoolcreator_back') ?></button>
    <button class="btn btn-default pull-right btn-steps tcf-validate" data-curstep="6" data-nxtstep="7"><?php echo $this->translate('tr_melistoolcreator_next') ?></button>
</div>
