<div id="<?php echo $this->id; ?>" class="steps-content">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <?php
                if (!$this->finalized) {
                    $form = $this->form;
                    echo $this->form()->openTag($form);
            ?>
                    <div class="melis-tc-final-content">
                        <h3><?php echo $this->translate('tr_melistoolcreator_finalization') ?></h3>
                        <p><?php echo $this->translate('tr_melistoolcreator_finalization_desc') ?></p>
                        <p>
                            <i class="fa fa-check-square-o text-success fa-lg"></i>
                            <?php echo $this->formElement($form->get('tcf-activate-tool')->setChecked(true)).' '.$this->translate('tr_melistoolcreator_finalization_activate_module') ?>
                        </p>
                        <p><?php echo $this->translate('tr_melistoolcreator_finalization_activation_note') ?></p>
                    </div>
            <?php
                    echo $this->form()->closeTag();
                }else{
            ?>
                <div class="alert alert-default" role="alert">
                    <i class="fa fa-thumbs-o-up fa-5x fa-fw pull-left text-success"></i>
                    <p><strong><?php echo $this->translate('tr_melistoolcreator_finalization_success_title') ?></strong></p>

                    <?php if ($this->restartRequired){ ?>
                        <p><?php echo $this->translate('tr_melistoolcreator_finalization_success_desc_with_counter') ?></p>
                    <?php }else{ ?>
                        <p><?php echo $this->translate('tr_melistoolcreator_finalization_success_desc') ?></p>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
        <div class="col-md-3"></div>
    </div>

    <?php if (!$this->finalized){ ?>
        <button class="btn btn-default btn-steps" data-curstep="8" data-nxtstep="7"><?php echo $this->translate('tr_melistoolcreator_back') ?></button>
        <button class="btn btn-default pull-right btn-steps tcf-validate" data-curstep="8" data-nxtstep="8"><?php echo $this->translate('tr_melistoolcreator_next') ?></button>
    <?php } ?>

    <?php if ($this->restartRequired){ ?>
        <script>
            var tcResCd = parseInt($("#tc-restart-cd").text());
            var countDown = setInterval(function() {
                if (tcResCd < 1){
                    location.reload();
                    clearInterval(countDown);
                    $("#tc-restart-cd").parent("p").text("<?php echo $this->translate('tr_melistoolcreator_refreshing') ?>");
                }else{
                    tcResCd--;
                    $("#tc-restart-cd").text(tcResCd);
                }
            }, 1000);
        </script>
    <?php } ?>
</div>
