<div class="me-heading bg-white border-bottom" id="id_meliscore_tool_user_header" data-meliskey="meliscore_tool_user_header">
    <div class="row">
        <div class="me-hl col-xs-12 col-sm-12 col-md-12">
            <h1 class="content-heading"><?php echo $this->translate('tr_melistoolcreator')?></h1>
            <p><?= $this->translate('tr_melistoolcreator_description'); ?></p>
        </div>
    </div>
</div>