<div class="modal-content">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="glyphicons <?php echo ($this->id) ? 'pencil' : 'plus' ?>" data-toggle="tab" aria-expanded="true"><i></i> <?php echo $this->translate('tr_moduletpl_title') ?></a></li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" <?php echo $this->zoneconfig['conf']['id'] ?>>
                            <div class="row">
                                <div class="col-md-12">
                                    <?php
                                    $form = $this->moduleTplForm;
                                    $form->prepare();
                                    echo $this->form()->openTag($form);
                                    echo $this->melisFieldCollection($form);
                                    echo $this->form()->closeTag();
                                    ?>
                                    <div align="right">
                                        <a data-dismiss="modal" class="btn btn-danger pull-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_moduletpl_common_button_close')?></a>
                                        <a class="btn btn-success btnSaveModuleTpl"><i class="fa fa-save"></i>  <?php echo $this->translate('tr_moduletpl_common_button_save'); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>